# Generated by Django 4.1.7 on 2023-03-05 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_student_token_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=datetime.date(2023, 3, 5)),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_date",
            field=models.DateField(default=datetime.date(2023, 3, 5)),
        ),
        migrations.AlterField(
            model_name="student",
            name="token_id",
            field=models.CharField(default="33753453", max_length=150),
        ),
    ]
