# Generated by Django 4.1.7 on 2023-03-08 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_alter_attendance_date_alter_course_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=datetime.date(2023, 3, 8)),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_date",
            field=models.DateField(default=datetime.date(2023, 3, 8)),
        ),
        migrations.AlterField(
            model_name="student",
            name="token_id",
            field=models.CharField(default="59509977", max_length=150),
        ),
    ]
