# Generated by Django 4.1.7 on 2023-03-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_alter_attendance_date_alter_course_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="token_id",
            field=models.CharField(default="18832128", max_length=150),
        ),
    ]
