# Generated by Django 4.1.7 on 2023-03-05 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_addcashtowallet_recepient_addcashtowallet_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addcashtowallet",
            name="date",
            field=models.DateField(default=datetime.date(2023, 3, 5)),
        ),
        migrations.AlterField(
            model_name="givesalary",
            name="date",
            field=models.DateField(default=datetime.date(2023, 3, 5)),
        ),
        migrations.AlterField(
            model_name="paytocourse",
            name="date",
            field=models.DateField(default=datetime.date(2023, 3, 5)),
        ),
    ]
